### ISSUE TITLE
How to correctoy read reset reasons?

### ISSUE THREAD

**Issue by fcuzzocrea** [polarfire-soc/platform#3] opened 2021-11-09 09:30 UTC
I am stumbling upon an unexpected behavior of the ICICLE Kit when reading the SYSREG->RESET_SR register to retrieve the cause of reset upon startup.

The weird behavior is that when I check SYSREG->RESET_SR value I get:

- Power cycle: 0x1ff
- Soft reset (SYSREG->MSS_RESET_CR = 0xdead): 0x1c7
- Reset from debugger (JTAG): 0xcf

Multiple of the 8 bits which are assigned to a specific reset cause are set to 1, which is an unexpected behavior.

Immediately after reading SYSREG->RESET_SR to a stack variable, I clear the register to 0x0 as requested by documentation in the header file https://github.com/polarfire-soc/platform/blob/13c8cc74e445008bf8615097d44ea28af4ff8d97/mpfs_hal/common/mss_sysreg.h#L135
Once I do this, the value stored in SYSREG->RESET_SR is 0x40, which would correspond to GPIO reset (?)

Thanks

**Comment by nitindeshpande** [comment] 2021-11-10 03:54
@fcuzzocrea, That sounds strange. We are looking into this. Will get back to you with more information soon.

**Comment by fcuzzocrea** [comment] 2021-11-10 09:07
Thanks!

**Comment by fcuzzocrea** [comment] 2021-11-20 19:23
Is there any update on this ?.?

**Comment by nitindeshpande** [comment] 2021-12-01 02:00
@fcuzzocrea, Quick update,
We have been able to reproduce the behavior you see with RESET_SR and that does not match the register description.
We are investigating this further. Will keep this thread updated.

**Comment by fcuzzocrea** [comment] 2021-12-01 05:50
Thanks!

**Comment by nitindeshpande** [comment] 2021-12-14 08:54
Sorry that it is taking longer than expected. 
So far, what we understand is that the documentation of this register may need an update. 
We will confirm the details once we have them documented.

**Comment by fcuzzocrea** [comment] 2021-12-15 18:24
Alright, thanks!!

**Comment by fcuzzocrea** [comment] 2022-02-28 10:34
Are there any update on this?

**Comment by nitindeshpande** [comment] 2022-02-28 11:08
Hello,

The reset value of all the bits is shown as 1 and that seems to be one reason for the confusion.

To read the RESET_SR, the process needs to be followed as below.
    - Very early in the E51 boot sequence read the RESET_SR register and store it in a variable.
    - Immediately write 0 into to arm it for the next cycle.
    - After this, a reset event e.g soft_reset will cause its bit to go to ‘1’ 

Note also that there may be multiple bits set in that register depending on the root cause of the reset.
For example: When the MSS is rebooted by the debugger, it will cause the SCB_MSS_RESET and SCB_CPU_RESET bits to be asserted as well.

RESET_SR = 0x1c7  => All resets happened EXCEPT watchdog, fabric and debugger. CPU Soft Reset being the root cause.
RESET_SR = 0xcf  => All resets happened EXCEPT watchdog and fabric. Debugger being the root cause.

The [register description](https://www.microsemi.com/document-portal/doc_download/1244581-polarfire-soc-register-map) will be updated.

**Comment by nitindeshpande** [comment] 2022-03-01 03:10
Hi,
The MPFS_HAL does not read/write to that register at present, so it can be done as the first thing in the e51().

**Comment by nitindeshpande** [comment] 2022-03-10 03:07
I hope the information that you were looking for is available to you. The register description update is underway.
Will close this issue. Feel free to revert if you have more questions.

**Closed by nitindeshpande** 2022-03-10 03:07 UTC

**Comment by fcuzzocrea** [comment] 2024-11-14 09:40
Is there any news on this ? I still do not find the register description update.
